### ISSUE TITLE
feature request: Select/Switch Projects from arDesktop/arLoad

### ISSUE THREAD

**Issue by quaam** [alexanderrichtertd/plex#26]
are there plans to add this to a future release? I have multiple projects and currently (if I'm not mistaken) the only way is to manually change the project in pipeline.yml and reload arDesktop. If there was a way of switching projects from arDesktop or when loading from arLoad, it would great. 
Thoughts?

**Comment by alexanderrichtertd** [comment]
as you can see from my reply time there are no future releases planned.
this repo should be a basic concept for code and wiki so you have a good starting point from here. 
that's why there no production scripts (besides load,save...)

Change projects is possible you need to override the ENV and refill arDesktop again.
A little bit tricky but doable if it is worth the time for you.

Thx for using Plex!

**Comment by alexanderrichtertd** [comment]
Let me know if you added this feature else I don't see a strong necessity for it at the moment to keep things as simple as possible.
