### ISSUE TITLE
Dependencies, not clear.

### ISSUE THREAD

**Issue by rulosmuchos** [alexanderrichtertd/plex#27]
after installing python 2.7
adding to PYTHONPATH
    - ~\00_pipeline\plex\exe
    - ~\00_pipeline\plex\exe\extern

I'm getting "ImportError: cannot import name QtWidgets"... should I:
    - install qt ?
    - install and point qt to PySide2?
    - reread the documentation?

greets.

**Comment by rulosmuchos** [comment]
Finally i got Plex up and running in MY. Sadly arDesktop no launching. 
Another question: There is a way to launch Plex into MY without installing python27?

**Comment by alexanderrichtertd** [comment]
The desktop app is a operation system thing so it could be a problem with the functions I am using.
If you want to have look, it is probably **lib/utils/arDesktop.py** line 143+
Should you find a more stable command - let me know so I can replace it.

Is MY=Maya?
If your Maya has an accessible Python folder you can add it to PYTHONPATH. Globally or in the BATCH since it has to be found BEFORE you use the first python script.

How did you fix your Qt issue?

**Comment by rulosmuchos** [comment]
I was loading redundant modules .. I cleaned it up ran it cleaned and worked... I started extending it.. case closed
