### ISSUE TITLE
save/version up with artist name at the end

### ISSUE THREAD

**Issue by compositorxyz** [alexanderrichtertd/plex#28]
![plex_01](https://user-images.githubusercontent.com/48181988/54472333-bfb52e00-4801-11e9-9644-a546bf9fe211.PNG)

I want to put artist name in the end of the nuke script, I tried to change **rules** file by adding this: **_{user}**
```
SCENES:
  assets: "{set}/{asset}/{task}/{status}/{asset}_{task}_{version}_.{extension}"
  shots : "{asset}/{task}/{status}/{asset}_{task}_{version}_{user}.{extension}"
  render: "{asset}/{task}/{status}/{asset}_{task}_{version}.{frame}.{extension}"
```

Now I have the name I want, but I guess it's not going work properly if other artists will version it up.

And inside arSaveAs.py I've changed [:2] from 2 to 3 characters.
```
def update_file(self):
        if self.wgSaveAs.cbxScene.currentText():
            status_text = '/' + self.data['rules']['STATUS']['work']
            if self.new_file: extension = Tank().software.extension
            else: extension = ''
            new_item = self.data['rules']['SCENES'][self.wgSaveAs.cbxScene.currentText()]
            new_item = new_item.format(set       = self.wgSaveAs.cbxSet.currentText(),
                                       asset     = self.wgSaveAs.cbxAsset.currentText(),
                                       task      = self.wgSaveAs.cbxTask.currentText(),
                                       status    = self.data['rules']['STATUS']['work'],
                                       version   = self.data['rules']['FILE']['version'].replace(r'\d','0').replace('_',''),
                                       user      = **getpass.getuser()**[:2]**.lower(),**
                                       extension = extension,
                                       frame     = self.data['rules']['start_frame'])

            if self.new_file: status_text += '/' + os.path.basename(new_item)
            self.save_file = self.save_dir + '/' + new_item
```

Will be so cool to add a variable such as nickname (Abbreviation), so it's easy to give any name to the artist, like:
name:     Alexander Richter
position: Technical Director

rights: 'admin'

**abb: "ari"**
```
#*********************************************************************
# content   = user data
# version   = 0.0.1
# date      = 2017-01-01
#
# license   = MIT
# copyright = Copyright 2017 Animationsinstitut
# author    = Alexander Richter <pipeline@richteralexander.com>
#*********************************************************************
# This source file has been developed within the scope of the
# Technical Director course at Filmakademie Baden-Wuerttemberg.
# http://td.animationsinstitut.de
#*********************************************************************

name:     Alexander Richter
position: Technical Director

rights: 'admin'
```

Thanks a lot for all your work!

**Comment by alexanderrichtertd** [comment]
Thanks that is a great comment.
I thought about this too:

1. In **users** there are users.initials (currently at 2 chars) which you can and should be used here
https://github.com/alexanderrichtertd/plex/blob/master/lib/classes/users.py
Personally I would autonegerate as much as possible to avoid to much manual typing.

2. You're right it will currently not work with versionUp but it wouldn't be complex to add. Basically rebuilding the path on every version up. Since you have all the informations you can do it systematically (after vXXX in dependens of the config file).
Since it is more of a rare case 2 different people working on the same shot/asset I was ignoring this exception also because I would rather have save such informations stored in a DATABASE (sql) which is more clean and easier to read.

Keep it up! Hope this pipeline could give worth to your work.

Best, Alex

**Comment by alexanderrichtertd** [comment]
I removed names completely from the file name template and store them in the meta data.
Seems cleaner and easier to handles - also solved your problem.
